from django.conf.urls import url
from django.urls import path

from .views import (
    ActivateDeactivatePlayerView,
    AdminSponserView,
    AdminView,
    AffiliatedPlayersAjaxView,
    AgentAjaxView,
    AgentCreditAjaxView,
    AgentsView,
    AlchemyPayReportView,
    ApproveAffiliateRequest,
    ApproveOffmarketWithdrawalRequest,
    ApproveWithdrawalRequest,
    AutomatedBonusView,
    BetBonusView,
    BonusPercentageView,
    BonusPermissionView,
    BonusesView,
    CasinoGameAjaxView,
    CasinoManagementProviderView,
    CmsPromotionsCreateView,
    CmsPromotionsDisableView,
    CmsPromotionsEditView,
    CmsPromotionsView,
    EditProviderView,
    ProviderView,
    CasinoManagementView,
    CasinoProviderAjaxView,
    ChatHistoryTabView,
    ChatHistoryView,
    CheckLogin,
    CreateAdmin,
    CreateAdminSponserView,
    CreateAffiliates,
    CreateAgent,
    CreateDealer,
    CreateOffMarketGameView,
    CreatePlayer,
    CreateStaff,
    CreateWithdrawalRequest,
    CreditAjaxView,
    CsrQueryView,
    DashboardView,
    DealerAjaxView,
    DealerCreditAjaxView,
    DealerView,
    DefaultAffiliateSetingsView,
    DefaultSettingsView,
    DeleteAdminSponser,
    DeleteOffmarketGame,
    DetailBonusView,
    DisableLosingBonusView,
    EditAdminSponserView,
    EditOffMarketGameView,
    EnableBonusView,
    EnableDisableCashbackView,
    EnableDisableCasinoView,
    EnableDisableLiveCasinoView,
    HomeView,
    CasinoBetslipReportView,
    InitiatePaymentView,
    LoginView,
    LogoutView,
    NowPaymentsReportView,
    OffMarketGamessView,
    OffmarketPendingWithdrawalsview,
    OtpPermissionView,
    PaymentDelayView,
    PendingAffiliateRequests,
    PendingWithdrawalsview,
    PlayersView,
    PlayerAjaxView,
    PlayerTransactionsView,
    ProfitView,
    QueryStatus,
    SaveAccountDetails,
    SetCashbackView,
    SetTimezoneView,
    SettingsView,
    SpinToWinGameStatus,
    SpinToWinProviderStatus,
    StaffAjaxView,
    StaffsView,
    TransactionListView,
    UpdateAgent,
    UpdateAutomatedBonusView,
    UpdateDealer,
    UpdatePlayer,
    UpdateStaff,
    UserCashtag,
    UserGamesView,
    UserProfitView,
    TransactionReportView,
	DownloadTransactionReport,
    CashbackPermissionView,
    JackpotPermissionView,
    SaveBetslipBonusPercentage,
    AdminBetslipBonusPermissionAjax,
    ChangeAgentBetslipBonusAjax,
    SpecialAgentPermissionView ,
    SpecialAgentLogoView,
    WithdrawalCurrenciesView,
    WithdrawalCurrencyAjaxView,
    WithdrawalCurrencyStatus,
    makeSpecialAgentView,
    SpecialAgentLogoDeleteView,
    GetSpecialAgentLogoView,
    AdminBannersView,
    DeleteAdminBanner,
    CreateAdminBannerView,
    CMSAboutView,
    CMSContactView,
    CRMView,
    CreateCrmTemplateView,
    ManageCrmTemplateAjax,
    EditCrmTemplateAjax,
    SendTemplateAjax,
    CMSPrivacyPolicyView,
    CmsFAQView,
    TermsConditinosView,
    CookiePolicyView,
    IntroductionView,
    SettingsLimitsView,
    UserEmailAjaxView,
    SetPlayerBettingLimitView,
    SignUpBonusView,
    LosingBonusView,
    ReferralBonusView,
    SignUpBonusPermissionView,
    EditBonusView,
    LosingBonusPermissionView,
    DepositPermission,
    DepositBonusView,
    ReferAFriendBonusPermission,
    PromotionPageView,
    CreatePromotionPageView,
    DeletePromotionPage,
    EditPromotionPageAjax,
    EditAdminBannerView,
    SocialLinkView,
    CreateSocialLinkView,
    DeleteSocialLinkView,
    EditSocialLinkAjax,
    FooterPageView,
    PagesView,
    CreatePageView,
    DeletePage,
    EditPageAjax,
    TogglePage,
    CategoryView,
    CreateCategoryView,
    DeleteCategory,
    EditCategoryAjax,
    FooterPageAjax,
    CreateFooterPageView,
    EditFooterPageView,
    DeleteFooterPageView,
    DetailSocialLinkAjax,
    VerifyPlayer,
    SMSView,
    CreateSMSTemplateView,
    EditSMSTemplateAjax,
    ManageSMSTemplateAjax,
    SendSMSTemplateAjax,
    NotificationView,
    CreateNotes,
    DeleteNoteAjaxView,
    UpdateNoteAjaxView,
    ComingSoonPermissionView,
    ComingSoonPageView,
    ComingSoonAjaxView,
    StaffWalletAndTransactionsView,
    ChatRoomView,
    OffMarketReportView,
    EditOffmarketTransactionGame,
    DeleteOffmarketTransaction,
    LeaveRoomview,
    is_room_active,
    Check_staff,
    SpintheWheelView,
    AddSpinDetailsView,
    MinimumSpinAmountView,
    RemoveSpinDetailsView,
    CashDeatilsView,
    CashAppReportView,
    PaymentUpdateCashapp,
    CashappQrView,
    CashAppListView,
    CreateUserGamesView,
    EditUserGamesView,
    BonusTransactionReportView,
    ChatInboxView,
    ChatInboxHistoryListView,
    ChatInboxHistoryDetailView,
    OffMarketGameView,
    OffMarketCreditAjaxView,
    CasinoTransactionsView,
    CasinoCategoryView,
    CasinoCategoryHeaderManagementView,
    CasinoHeaderCategoryStatus,
    TournamentListView,
    CreateTournamentView,
    EditTournamentView,
    TournamentDetailView,
    EmailTemplateView,
    AddEmailTemplateView,
    ManageEmailTemplateAjax,
    EditEmailTemplateAjax,
    CmsImageUploadView,
    CmsBonusDetailListView,
    CreateCmsBonusDetailView,
    EditCmsBonusDetailView,
    PromoCodeAjaxView,
    DeleteCmsBonusDetailView,
    RolesView,
    CreateRoleView,
    UpdateRoleView,
    UserListByRoleView,
    CreateUserByRole,
    UpdateUserByRole,
    FortunepandasGamesManagementView,
    FortunepandasGameAjaxView,
    FortunepandasCategoryView,
    FortunepandasGameStatus,
    MnetReportView,
    MaintenanceModeAjaxView,
    PagesContentView,

)

app_name = "Admin"


urlpatterns = [
    url(r"^login/", LoginView.as_view(), name="login"),
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^players/", PlayersView.as_view(), name="players"),
    url(r"^update-player/", UpdatePlayer.as_view(), name="update-player"),
    url(r"^user-profit/(?P<user_id>\w+)/$", UserProfitView.as_view(), name="user-profit"),
    url(r"^user-off-market-deatils/(?P<user_id>\w+)/$", OffMarketGameView.as_view(), name="user-off-market-deatils"),
    url(r"^create-player/", CreatePlayer.as_view(), name="create-player"),
    url(r'^player-ajax/$', PlayerAjaxView.as_view(), name='player-ajax'),
    url(r"^dealer-ajax/$", DealerAjaxView.as_view(), name="dealer-ajax"),
    url(r"^agent-ajax/$", AgentAjaxView.as_view(), name="agent-ajax"),
    url(r'^player-ajax/$', PlayerAjaxView.as_view(), name='player-ajax'),
    url(r"^agents/", AgentsView.as_view(), name="agents"),
    url(r"^update-agent/", UpdateAgent.as_view(), name="update-agent"),
    url(r"^create-agent/", CreateAgent.as_view(), name="create-agent"),
    url(r"^dealers/", DealerView.as_view(), name="dealers"),
    url(r"^create-dealers/", CreateDealer.as_view(), name="create-dealer"),
    url(r"^update-dealer/", UpdateDealer.as_view(), name="update-dealer"),
    url(r"^credit-ajax/$", CreditAjaxView.as_view(), name="credit-ajax"),
    url(r"^payment-delay-ajax/$", PaymentDelayView.as_view(), name="payment-delay-ajax"),
    url(r"^agent-credit-ajax/$", AgentCreditAjaxView.as_view(), name="agent-credit-ajax"),
    url(r"^dealer-credit-ajax/$", DealerCreditAjaxView.as_view(), name="dealer-credit-ajax"),
    url(r"^save-account-details/$", SaveAccountDetails.as_view(), name="save-account-details"),
    url(r"^logut/$", LogoutView.as_view(), name="logout"),
    url(r"^admins/", AdminView.as_view(), name="admins"),
    url(r"^create-admin/", CreateAdmin.as_view(), name="create-admin"),
    url(r"^transactions/", TransactionListView.as_view(), name="transactions"),
    url(r"^player-transactions/", PlayerTransactionsView.as_view(), name="player_transactions"),
    url(r"^set-timezone/", SetTimezoneView.as_view(), name="set-timezone"),
    url(r"^profit/", ProfitView.as_view(), name="profit"),
    url(r"^manage-casino/", EnableDisableCasinoView.as_view(), name="manage-casino"),
    url(r"^manage-live-casino/", EnableDisableLiveCasinoView.as_view(), name="manage-live-casino"),
    url(r"^manage-cashback/", EnableDisableCashbackView.as_view(), name="manage-cashback"),
    url(r"manage-jackpot-permissions/", JackpotPermissionView.as_view(), name="manage-jackpot-permissions"),
    url(r"^manage-cashback-status/", CashbackPermissionView.as_view(), name="manage-cashback-status"),
    url(r"^manage-player/", ActivateDeactivatePlayerView.as_view(), name="manage-player"),
    url(r"^verify-player/", VerifyPlayer.as_view(), name="verify-player"),
    url(r"manage-special-agent-permissions/", SpecialAgentPermissionView.as_view(), name="manage-special-agent-permissions"),
    url(r"^special-agent-logo/", SpecialAgentLogoView.as_view(), name="special-agent-logo"),
    url(r"^delete-special-agent-logo-/", SpecialAgentLogoDeleteView.as_view(), name="delete-special-agent-logo"),
    url(r"^delete-admin-banner/", DeleteAdminBanner.as_view(), name="delete-admin-banner"),
    url(r"^get-special-agent-logo/", GetSpecialAgentLogoView.as_view(), name="get-special-agent-logo"),
    
    url(r"make-special-agent/", makeSpecialAgentView.as_view(), name="make-special-agent"),
    url(r"^check-login/", CheckLogin.as_view(), name="check-login"),
    url(r"^setting/", SettingsView, name="setting"),
    url(r'^dashboard-ajax/$', DashboardView.as_view(), name='dashboard-ajax'),
    url(r"^payment/", InitiatePaymentView.as_view(), name="payement"),
    url(r"^transactions-report/", TransactionReportView.as_view(), name="transactions-report"),
    url(r"^bonus-report/", BonusTransactionReportView.as_view(), name="bonus-report"),
    url(r"^cashapp-report/", CashAppReportView.as_view(), name="cashapp-report"),
    
    url(r"^offmarket-report/", OffMarketReportView.as_view(), name="offmarket-report"),
	url(r"^download-transactions-report/", DownloadTransactionReport.as_view(), name="download-transactions-report"),
    url(r"^manage-otp-permissions/", OtpPermissionView.as_view(), name="manage-otp-permissions"),
    url(r"^bonuses/", BonusesView.as_view(), name="bonuses"),
    url(r"^bonus-percentage/", BonusPercentageView.as_view(), name="bonus-percentage"),
    url(r"^disable-bonus/", DisableLosingBonusView.as_view(), name="disable-bonus"),
    url(r"^enable-bonus/", EnableBonusView.as_view(), name="enable-bonus"),
    url(r"^manage-bonus-permissions/", BonusPermissionView.as_view(), name="manage-bonus-permissions"),
    url(r"^save-betslip-bonus-percentage/", SaveBetslipBonusPercentage.as_view(), name="save-betslip-bonus-percentage"),
    url(r"^admin-betslip-bonus-permission-ajax/", AdminBetslipBonusPermissionAjax.as_view(), name="admin-betslip-bonus-permission-ajax"),
    url(r"^change-agent-betslipbonus-ajax/", ChangeAgentBetslipBonusAjax.as_view(), name="change-agent-betslipbonus-ajax"),
    url(r"^set-cashback-view/", SetCashbackView.as_view(), name="set-cashback-view"),
    url(r"^admin-banner/", AdminBannersView.as_view(), name="admin-banner"),
    url(r"^create-admin-banner/", CreateAdminBannerView.as_view(), name="create-admin-banner"),
    url(r"^cms-about/", CMSAboutView.as_view(), name="cms-about"),
    url(r"^cms-contact/", CMSContactView.as_view(), name="cms-contact"),
    url(r"^crm/", CRMView.as_view(), name="crm"),
    url(r"^create-crm-template/", CreateCrmTemplateView.as_view(), name="create-crm-template"),
    url(r"^manage-crm-template/", ManageCrmTemplateAjax.as_view(), name="manage-crm-template"),
    url(r"^edit-crm-template/", EditCrmTemplateAjax.as_view(), name="edit-crm-template"),
    url(r"^send-crm-template/", SendTemplateAjax.as_view(), name="send-crm-template"),
    url(r"^cms-privacy-policy/", CMSPrivacyPolicyView.as_view(), name="cms-privacy-policy"),
    url(r"^cms-faq/", CmsFAQView.as_view(), name="cms-faq"),
    url(r"^cms-terms-conditinos/", TermsConditinosView.as_view(), name="cms-terms-conditinos"),
    url(r"^cms-cookie-policy/", CookiePolicyView.as_view(), name="cms-cookie-policy"),
    url(r"^cms-introduction/", IntroductionView.as_view(), name="cms-introduction"),
    url(r"^cms-settings-limits/", SettingsLimitsView.as_view(), name="cms-settings-limits"),
    url(r"^user-email-ajax/", UserEmailAjaxView.as_view(), name="user-email-ajax"),
    url(r"^set-player-betting-limit/", SetPlayerBettingLimitView.as_view(), name="set-player-betting-limit"),
    url(r'^signup-bonus/(?P<promo_code>[-\w]+)/$', DetailBonusView.as_view(), name='detail-promocode'),
    url(r"^signup-bonus/", SignUpBonusView.as_view(), name="sign-up-bonus"),
    url(r"^automated-bonus/", AutomatedBonusView.as_view(), name="automated-bonus"),
    url(r"^update-automated-bonus/",UpdateAutomatedBonusView.as_view(), name="update-automated-bonus"),
    url(r"^losing-bonus/", LosingBonusView.as_view(), name="losing-bonus"),
    url(r"^referral-bonus/", ReferralBonusView.as_view(), name="referral-bonus"),
    url(r"^enable-signup-bonus-permissions/", SignUpBonusPermissionView.as_view(), name="enable-signup-bonus-permissions"),
    url(r"^edit-bonuses/", EditBonusView.as_view(), name="edit-bonuses"),
    url(r"^enable-losing-bonus-permissions/", LosingBonusPermissionView.as_view(), name="enable-losing-bonus-permissions"),
    url(r"deposit-permissions/", DepositPermission.as_view(), name="deposit-permissions"),
    url(r"^deposit-bonus/", DepositBonusView.as_view(), name="deposit-bonus"),
    url(r"^enable-referral-bonus-permissions/", ReferAFriendBonusPermission.as_view(), name="enable-referral-bonus-permissions"),
    url(r"^promotion-page/", PromotionPageView.as_view(), name="promotion-page"),
    url(r"^create-promotion-page/", CreatePromotionPageView.as_view(), name="create-promotion-page"),
    url(r"^delete-promotion-page/", DeletePromotionPage.as_view(), name="delete-promotion-page"),
    url(r"^edit-promotion-page/", EditPromotionPageAjax.as_view(), name="edit-promotion-page"),
    url(r"^promotion/$", CmsPromotionsView.as_view(), name="cms-promotions"),
    url(r"^promotion/create/", CmsPromotionsCreateView.as_view(), name="cms-promotions-create"),
    url(r"^promotion/(?P<pk>\d+)/edit/$", CmsPromotionsEditView.as_view(), name="cms-promotions-edit"),
    url(r"^promotion/(?P<pk>\d+)/disable/$", CmsPromotionsDisableView.as_view(), name="cms-promotions-disable"),
    url(r"^edit-admin-banner/", EditAdminBannerView.as_view(), name="edit-admin-banner"),
    url(r"^social-link/", SocialLinkView.as_view(), name="social-link"),
    url(r"^create-social-link/", CreateSocialLinkView.as_view(), name="create-social-link"),
    url(r"^delete-social-link/", DeleteSocialLinkView.as_view(), name="delete-social-link"),
    url(r"^edit-social-link/", EditSocialLinkAjax.as_view(), name="edit-social-link"),
    url(r"^footer-page/", FooterPageView.as_view(), name="footer-page"),
    url(r"^pages/", PagesView.as_view(), name="pages"),
    url(r"^page-content/", PagesContentView.as_view(), name="page-content"),
    url(r"^create-page/", CreatePageView.as_view(), name="create-page"),
    url(r"^delete-page/", DeletePage.as_view(), name="delete-page"),
    url(r"^toggle-page/", TogglePage.as_view(), name="toggle-page"),
    url(r"^edit-page/", EditPageAjax.as_view(), name="edit-page"),
    url(r"^categorys/", CategoryView.as_view(), name="category"),
    url(r"^create-category/", CreateCategoryView.as_view(), name="create-category"),
    url(r"^delete-category/", DeleteCategory.as_view(), name="delete-category"),
    url(r"^edit-category/", EditCategoryAjax.as_view(), name="edit-category"),
    url(r"^footer-pages-ajax/$", FooterPageAjax.as_view(), name="footer-pages-ajax"),
    url(r"^create-footer/", CreateFooterPageView.as_view(), name="create-footer"),
    url(r"^edit-footer-page/", EditFooterPageView.as_view(), name="edit-footer-page"),
    url(r"^delete-footer-page/", DeleteFooterPageView.as_view(), name="delete-footer-page"),
    url(r"^detail-social-link/", DetailSocialLinkAjax.as_view(), name="detail-social-link"),
    url(r"^sms/", SMSView.as_view(), name="sms"),
    url(r"^create-sms-template/", CreateSMSTemplateView.as_view(), name="create-sms-template"),
    url(r"^edit-sms-template/", EditSMSTemplateAjax.as_view(), name="edit-sms-template"),
    url(r"^manage-sms-template/", ManageSMSTemplateAjax.as_view(), name="manage-sms-template"),
    url(r"^send-sms-template/", SendSMSTemplateAjax.as_view(), name="send-sms-template"),
    url(r"^notification/", NotificationView.as_view(), name="notification"),
    url(r"^casino-report/", CasinoBetslipReportView.as_view(), name="casinobetslip-report"),
    url(r"^casino-management-provider-list/", CasinoManagementProviderView.as_view(), name="casino-management-provider-list"),
    url(r"^edit-provider/", EditProviderView.as_view(), name="edit-provider"),
    url(r"^provider-manager/", ProviderView.as_view(), name="provider-manager"),
    url(r"^manage-spin-to-win-provider-status/", SpinToWinProviderStatus.as_view(), name="manage-spin-to-win-provider-status"),
    url(r"^casino-management-game-list/", CasinoManagementView.as_view(), name="casino-management-game-list"),
    url(r"^casino-management-game-category/", CasinoCategoryHeaderManagementView.as_view(), name="casino-management-game-category"),
    url(r"^casino-management-categories-status/", CasinoHeaderCategoryStatus.as_view(), name="casino-management-categories-status"),
    url(r"^manage-spin-to-win-game-status/", SpinToWinGameStatus.as_view(), name="manage-spin-to-win-game-status"),
    # TODO: 
    url(r"^casino-provider-ajax/$", CasinoProviderAjaxView.as_view(), name="casino-provider-ajax"),
    url(r"^casino-game-ajax/$", CasinoGameAjaxView.as_view(), name="casino-game-ajax"),
    url(r"^delete-admin-ads/", DeleteAdminSponser.as_view(), name="delete-admin-ads"),
    url(r"^edit-admin-ads/", EditAdminSponserView.as_view(), name="edit-admin-ads"),
    url(r"^admin-ads/", AdminSponserView.as_view(), name="admin-ads"),
    url(r"^create-admin-ads/", CreateAdminSponserView.as_view(), name="create-admin-ads"),
    url(r"^create-affiliates/", CreateAffiliates.as_view(), name="create-affiliates"),
    url(r"^affiliated-players-ajax/", AffiliatedPlayersAjaxView.as_view(), name="affiliated-players-ajax"), 
    url(r"^bet-bonus/", BetBonusView.as_view(), name="bet-bonus"), 
    # url(r"^casino-management-game-list/", CasinoManagementView.as_view(), name="casino-management-game-list"),
    # url(r"^casino-management-provider-list/", CasinoManagementProviderView.as_view(), name="casino-management-provider-list"),
    url(r"^pendingwithdrawals/", PendingWithdrawalsview.as_view(), name="pending-withdrawals"),
    url(r"^update-withdrawal-request-status/", ApproveWithdrawalRequest.as_view(), name="update-withdrawal-request-status"),
    url(r"^nowpayments-report/", NowPaymentsReportView.as_view(), name="nowpayments-report"),
    url(r"^withdrawal-currency-status/", WithdrawalCurrencyStatus.as_view(), name="withdrawal-currency-status"),
    url(r"^withdrawal-currencies-list/", WithdrawalCurrenciesView.as_view(), name="withdrawal-currencies-list"),
    url(r"^withdrawal-currency-ajax/$", WithdrawalCurrencyAjaxView.as_view(), name="withdrawal-currency-ajax"),
    url(r"^create-notes/", CreateNotes.as_view(), name="create-notes"),
    url(r"^delete-note/", DeleteNoteAjaxView.as_view(), name="delete-note"),
    url(r"^update-note/", UpdateNoteAjaxView.as_view(), name="update-note"),
    url(r"^manage-coming-soon-permissions/", ComingSoonPermissionView.as_view(), name="manage-coming-soon-permissions"),
    url(r"^coming_soon_page/", ComingSoonPageView.as_view(), name="coming_soon_page"),
    url(r"^coming_soon_ajax/", ComingSoonAjaxView.as_view(), name="coming_soon_ajax"),
    url(r"^maintenance_mode_ajax/", MaintenanceModeAjaxView.as_view(), name="maintenance_mode_ajax"),
    url(r"^pendingaffiliates/", PendingAffiliateRequests.as_view(), name="pending-affiliates"),
    url(r"^update-affiliate-request-status/", ApproveAffiliateRequest.as_view(), name="update-affiliate-request-status"),
    url(r"^default-affiliate-settings/", DefaultAffiliateSetingsView.as_view(), name="default-affiliate-settings"),
    url(r"^default-settings/", DefaultSettingsView.as_view(), name="default-settings"),
    
    url(r"^staff_wallet_and_transactions/", StaffWalletAndTransactionsView.as_view(), name="staff_wallet_and_transactions"),
    url(r"^staffs/", StaffsView.as_view(), name="staffs"),
    url(r"^update-staff/", UpdateStaff.as_view(), name="update-staff"),
    url(r"^create-staff/", CreateStaff.as_view(), name="create-staff"),
    url(r"^chatroom/", ChatRoomView.as_view(), name="chatroom"),
    url(r"^chat-history/", ChatHistoryView.as_view(), name="chat-history"),
    url(r"^withdrawal-request/", CreateWithdrawalRequest.as_view(), name="withdrawal-request"),
    url(r"^chat-history-tab/", ChatHistoryTabView.as_view(), name="chat-history-tab"),
    url(r"^user-cashtag/", UserCashtag.as_view(), name="user-cashtag"),
    url(r"^offmarket-games/", OffMarketGamessView.as_view(), name="offmarket-games"),
    url(r"^create-offmarket-game/", CreateOffMarketGameView.as_view(), name="create-offmarket-game"),
    url(r"^edit-offmarket-game/", EditOffMarketGameView.as_view(), name="edit-offmarket-game"),
    url(r"^create-user-game/", CreateUserGamesView.as_view(), name="create-user-game"),
    url(r"^edit-user-game/", EditUserGamesView.as_view(), name="edit-user-game"),
    url(r"^user-games/", UserGamesView.as_view(), name="user-games"),
    url(r'^staff-ajax/$', StaffAjaxView.as_view(), name='staff-ajax'),
    url(r'^csrquery/$', CsrQueryView.as_view(), name='csrquery'),
    url(r'^change-query-status/$', QueryStatus.as_view(), name='change-query-status'),
    url(r'^delete-offmarket/$', DeleteOffmarketGame.as_view(), name='delete-offmarket'),
    url(r"^offmarket-pending-withdrawals/", OffmarketPendingWithdrawalsview.as_view(), name="offmarket-pending-withdrawals"),
    url(r"^update-offmarket-withdrawal-request-status/", ApproveOffmarketWithdrawalRequest.as_view(), name="update-offmarket-withdrawal-request-status"),
    url(r'^delete-offmarket-transaction/$', DeleteOffmarketTransaction.as_view(), name='delete-offmarket-transaction'),
    url(r'^edit-offmarket-transaction/$', EditOffmarketTransactionGame.as_view(), name='edit-offmarket-transaction'),
    url(r"^alchemypay-report/", AlchemyPayReportView.as_view(), name="alchemypay-report"),

    url(r"^leave-room/", LeaveRoomview.as_view(), name="leave-room"),
    url(r"^is_room_active/", is_room_active, name="is_room_active"),
    url(r"^check_staff/", Check_staff, name="check_staff"),
    

    url(r"^spin-the-wheel/", SpintheWheelView.as_view(), name="spin-the-wheel"),
    url(r"^add-spin-details/", AddSpinDetailsView.as_view(), name="add-spin-details"),
    url(r"^min-spin-amount/", MinimumSpinAmountView.as_view(), name="min-spin-amount"),
    url(r"^remove-spin/", RemoveSpinDetailsView.as_view(), name="remove-spin"),
    url(r"^cash-deatils/", CashDeatilsView.as_view(), name="cash-deatils"),
    url(r"^reload_cash_app/", PaymentUpdateCashapp.as_view(), name="reload_cash_app"),    
    url(r"^cashapp-detail/", CashappQrView.as_view(), name="cashapp-detail"),
    url(r"^cashapp/", CashAppListView.as_view(), name="cashapp"),
    url(r"^inbox/", ChatInboxView.as_view(), name="inbox"),
    url(r"^inbox-history/", ChatInboxHistoryListView.as_view(), name="inbox-history-list"),
    url(r"^inbox-history-detail/", ChatInboxHistoryDetailView.as_view(), name="inbox-history-detail"),
    url(r"^off-market-credit/", OffMarketCreditAjaxView.as_view(), name="off-market-credit"),
    url(r"^casino-transactions/", CasinoTransactionsView.as_view(), name="casino-transactions"),
    url(r"^casino-categories/", CasinoCategoryView.as_view(), name="casino-categories"),
    url(r"^tournaments/", TournamentListView.as_view(), name="tournaments"),
    url(r"^create-tournament/", CreateTournamentView.as_view(), name="create-tournament"),
    url(r"^edit-tournament/", EditTournamentView.as_view(), name="edit-tournament"),
    url(r"^tournament-detail/", TournamentDetailView.as_view(), name="tournament-detail"),
    url(r"^email-templates/", EmailTemplateView.as_view(), name="email-templates"),
    url(r"^add-email-template/", AddEmailTemplateView.as_view(), name="add-email-template"),
    url(r"^manage-email-template/", ManageEmailTemplateAjax.as_view(), name="manage-email-template"),
    url(r"^edit-email-template/", EditEmailTemplateAjax.as_view(), name="edit-email-template"),
    url(r"^upload-cms-file/", CmsImageUploadView.as_view(), name="upload-cms-file"),
    url(r"^bonus-details/", CmsBonusDetailListView.as_view(), name="bonus-details"),
    url(r"^add-bonus-content/", CreateCmsBonusDetailView.as_view(), name="add-bonus-content"),
    url(r"^edit-bonus-content/", EditCmsBonusDetailView.as_view(), name="edit-bonus-content"),
    url(r"^available-promo-codes/", EditCmsBonusDetailView.as_view(), name="edit-bonus-content"),
    url(r'^promocodes-ajax/$', PromoCodeAjaxView.as_view(), name='promocodes-ajax'),
    url(r"^delete-bonus-content/$", DeleteCmsBonusDetailView.as_view(), name="delete-bonus-content"),
    url(r"^roles/(?P<role>[^/]+)/$", UserListByRoleView.as_view(), name="user-list-by-role"),
    url(r"^create-user/(?P<role>[^/]+)/$", CreateUserByRole.as_view(), name="create-user"),
    url(r"^update-user/(?P<role>[^/]+)/$", UpdateUserByRole.as_view(), name="update-user"),
    url(r"^roles/", RolesView.as_view(), name="roles"),
    url(r"^create-role/", CreateRoleView.as_view(), name="create-role"),
    url(r"^update-role/", UpdateRoleView.as_view(), name="update-role"),
    url(r"^fortunepandas-management-game-list/", FortunepandasGamesManagementView.as_view(), name="fortunepandas-management-game-list"),
    url(r"^fortunepandas-game-ajax/$", FortunepandasGameAjaxView.as_view(), name="fortunepandas-game-ajax"),
    url(r"^fortunepandas-categories/", FortunepandasCategoryView.as_view(), name="fortunepandas-categories"),
    url(r"^manage-fortunepandas-game-status/", FortunepandasGameStatus.as_view(), name="manage-fortunepandas-game-status"),
    url(r"^mnet-report/", MnetReportView.as_view(), name="mnet-report"),
]
