from django.conf.urls import url
from apps.users.views import (AboutCmsView, AddSpinWheelView, AdminAdsPublicDetailsView,
                              AdminPublicDetailsView, AffiiateRequestView, AffiliatedPlayers, BonusDetailView,
                              CashAppDetailsApi, CashappQrListView, CashbackView, ChangePassword, ChatSupportView,
                              CmsFAQView, CmsPrivacyPolicyView, CmsPromotionsView, ComingSoonPagesDeatilsView, ContactUsView,
                              CookiePolicyView,
                              CsrQueryView, FooterDeatilsView, ForgotPassword, FortunePandasAPIView,
                              FortunePandasCategoryAPIView, GetOTPView, GetSlug, IntroductionView, LoginAPIView,
                              Notification, OffMarketDepositView, OffmarketTransaction, OffMarketWithdrawView,
                              PagesDeatilsView, PlayerDeActiveView, PlayerEmailOTPsender, PlayerEmailOTPsender,
                              PromotionCmsView, QueueView, ReadMessageView, RecentMessagesView, RestrictedLoginView,
                              SetlanguageView, SetPlayerBettingLimitView, SetPlayerBlackoutView,
                              SetPlayerMaxSpendLimitView,
                              SettingsLimitsView, SignUpOTP, SignUpView, SpintheWheelDetailsAPIView, StaffDetailView,
                              TermsConditinosView, TipView, TransactionsAPIView, UserUpdateView, ValidatePromoCode,
                              ValidateReferralUser, ValidateSignUpPromoCode, VerifyOTPView, VerifyOTPView, VerifyToken,
                              OTPActionsView, CountriesView, NextSpinWheel)
    

app_name = "Users"

urlpatterns = [
    url(r"^login/?", LoginAPIView.as_view(), name="login"),
    url(r"^verify-token/?", VerifyToken.as_view(), name="verify_token"),
    url(r"^change-password/?", ChangePassword.as_view(), name="change_password"),
    url(r"^cashback/?", CashbackView.as_view(), name="cashback"),
    url(r"^signup/?", SignUpView.as_view(), name="signup"),
    url(r"^get-otp/?", GetOTPView.as_view(), name="get_otp"),
    url(r"^verify-otp/?", VerifyOTPView.as_view(), name="verify_otp"),
    url(r"^otp-actions/", OTPActionsView.as_view(), name="otp-actions"),
    url(r"^contact-us-details/?", ContactUsView.as_view(), name="contact-us-details"),
    url(r"^about-details/?", AboutCmsView.as_view(), name="about-details"),
    url(r"^promotions/?", PromotionCmsView.as_view(), name="promotion-details"),
    url(r"^notifications/?", CmsPromotionsView.as_view(), name="cms-promotions"),
    url(r"^close-account/?", PlayerDeActiveView.as_view(), name="close_account"),
    url(r"^set-max-spend-limit/?", SetPlayerMaxSpendLimitView.as_view(), name="set_max_spend_limit"),
    url(r"^user-blackout/?", SetPlayerBlackoutView.as_view(), name="user_blackout"),
    url(r"^privacy-policy-details/?", CmsPrivacyPolicyView.as_view(), name="privacy-policy-details"),
    url(r"^faq-details/?", CmsFAQView.as_view(), name="faq-details"),
    url(r"^terms-conditinos/?", TermsConditinosView.as_view(), name="terms-conditinos"),
    url(r"^cookie-policy/?", CookiePolicyView.as_view(), name="cookie-policy"),
    url(r"^introduction/?", IntroductionView.as_view(), name="introduction"),
    url(r"^settings-limits/?", SettingsLimitsView.as_view(), name="settings-limits"),
    url(r"^check-signup-promo-code/", ValidateSignUpPromoCode.as_view(), name="check-signup-promo-code"),
    url(r"^validate-promo-code/", ValidatePromoCode.as_view(), name="validate-promo-code"),
    url(r"^check-referral-user/", ValidateReferralUser.as_view(), name="check-referral-user"),
    url(r"^footer-details/?", FooterDeatilsView.as_view(), name="footer-details"),
    url(r"^footer-pages/?", PagesDeatilsView.as_view(), name="footer-pages"),
    url(r"^set-player-betting-limit/?", SetPlayerBettingLimitView.as_view(), name="set-player-betting-limit"),
    url(r"^notification/", Notification.as_view(), name="important-matches-list"),

    url(r"^userupdate/", UserUpdateView.as_view(), name="userupdate"),
    url(r"^slug", GetSlug.as_view(), name="slug"),
    url(r"^banner/?", AdminPublicDetailsView.as_view(), name="banner"),
    url(r"^send-email-otp", PlayerEmailOTPsender.as_view(), name="send-email-otp"),
    url(r"^forgot-password", ForgotPassword.as_view(), name="forgot-password"),
    url(r"^ads-banner/?", AdminAdsPublicDetailsView.as_view(), name="ads-banner"),
    url(r"^affiliated-players", AffiliatedPlayers.as_view(), name="affilliated-player"),
    # url(r"^send-email-otp", PlayerEmailOTPsender.as_view(), name="send-email-otp"),
    # url(r"^forgot-password", ForgotPassword.as_view(), name="forgot-password"),
    url(r"^extra-page/?", ComingSoonPagesDeatilsView.as_view(), name="extra-page"),
    url(r"^affiliate-requests/?", AffiiateRequestView.as_view(), name="affiliate-requests"),
    url(r"^otp-signup/?", SignUpOTP.as_view(), name="otp-signup"),
    url(r"^tip/?", TipView.as_view(), name="tip"),
    # url(r"^chat-queue/?", QueueView.as_view(), name="chat-queue"),
    url(r"^csr-query/?", CsrQueryView.as_view(), name="csr-query"),
    url(r"^recent-messages/?", RecentMessagesView.as_view(), name="recent-messages"),
    url(r"^restricted-login/?", RestrictedLoginView.as_view(), name="restricted-login"),
    url(r"^add-credit/?", OffMarketDepositView.as_view(), name="add-credit"),
    url('offmarket-transactions/', OffmarketTransaction.as_view(), name='offmarket-transactions'),
    url(r"offmarket-withdraw-request/", OffMarketWithdrawView.as_view(), name='offmarket-withdraw-request'),
    url(r"add-spin-wheel/", AddSpinWheelView.as_view(), name='add-spin-wheel'),
    url(r'next-spin-wheel/', NextSpinWheel.as_view(), name='next-spin-wheel'),
    url(r"spin-wheel-details/", SpintheWheelDetailsAPIView.as_view(), name='spin-wheel-details'),
    url(r"transactions/", TransactionsAPIView.as_view(), name='transactions-list'),
    url(r"cashapp-detail/", CashAppDetailsApi.as_view(), name='cashapp-detail'),
    url(r"^cashapp-qr-list/?", CashappQrListView.as_view(), name='cashapp-qr-list'),
    url(r"^chat-room/?", ChatSupportView.as_view(), name="chat-room"),
    url(r"^staff-detail/?", StaffDetailView.as_view(), name="staff-detail"),
    url(r"read_message_player", ReadMessageView.as_view(), name="read_message_player"),
    url(r"^set-language/?", SetlanguageView.as_view(), name="set-language"),
    url(r"^bonus-detail/?", BonusDetailView.as_view(), name="bonus-detail"),
    url(r"^fortunepandas-categories/?", FortunePandasCategoryAPIView.as_view(), name="fortunepandas-categories"),
    # url(r"^fortunepandas/?", FortunePandasAPIView.as_view(), name="fortunepandas"),

    url(r'^countries/?', CountriesView.as_view(), name='countries'),

]
