"""
Django settings for api_services project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime
import os

from apps.core.utils import get_env_var

from corsheaders.defaults import default_headers

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_var('SECRET_KEY')
ACCESS_KEY_ID = get_env_var("ACCESS_KEY_ID")
SECRET_ACCESS_KEY = get_env_var("SECRET_ACCESS_KEY")
AWS_REGION_NAME = get_env_var("AWS_REGION_NAME")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

DEFAULT_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jet.dashboard',
    'jet',
    'channels'
]


# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "PASSWORD": "mysecret"
#         }
#     }
# }

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "example"
    }
}

CACHE_TTL = 60 * 150

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'rollbar.contrib.django_rest_framework.post_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'TEST_REQUEST_RENDERER_CLASSES': (
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer'
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # TODO: remove session auth option before going to production
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'apps.core.jwt_token_authentication.CustomJSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',

    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'apps.core.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'apps.core.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

CORS_ALLOW_METHODS = ("DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT")


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS_ALL = True
CORS_ALLOW_CREDENTIALS = False

SWAGGER_SETTINGS = {
    'LOGIN_URL': 'rest_framework:login',
    'LOGOUT_URL': 'rest_framework:logout',
    'USE_SESSION_AUTH': True,
    'APIS_SORTER': 'alpha',
    'SHOW_REQUEST_HEADERS': True,
    'DOC_EXPANSION': 'none',
    'JSON_EDITOR': True,
    'SECURITY_DEFINITIONS': {
        "api_key": {
            "type": "apiKey",
            "name": "jwt",
            "in": "header"
        },
    },
}

THIRD_PARTY_APPS = [
    'mathfilters',
    'rest_framework',
    'rest_framework_swagger',
    'drf_yasg',
    'corsheaders',
    'django_filters',
    'django_celery_results',
    'django_crontab',
    'background_task',
    'django_coinpayments',
    'ckeditor',
    'ckeditor_uploader',
    'tinymce',
]



PROJECT_APPS = [
    'apps.core',
    'apps.users',
    'apps.pulls',
    'apps.bets',
    'apps.admin_panel',
    'apps.casino',
    'apps.payments',
]

MIDDLEWARE = [
    'apps.admin_panel.force_default_language_middleware.ForceDefaultLanguageMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'apps.admin_panel.middleware.UpdateLastActivityMiddleware',
]

ROOT_URLCONF = 'api_services.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "apps.admin_panel.context_processors.header_roles",
            ]
        },
    }
]

WSGI_APPLICATION = 'api_services.wsgi.application'

API_VERSION_URL = 'api/v0/'

LOCAL = os.environ.get('IS_LOCAL_ENV')

ENV_POSTFIX = get_env_var('ENV_POSTFIX')

AUTH_USER_MODEL = 'users.Users'

AUTHENTICATION_BACKENDS = [
    'apps.core.authentication_backends.BaseUserAuthentication'
]

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': get_env_var('DB_NAME'),
        'USER': get_env_var('DB_USER'),
        'PASSWORD': get_env_var('DB_PASSWORD'),
        'HOST': get_env_var('DB_HOST'),
        'PORT': get_env_var('DB_PORT'),
    }
}

rabbit_connection_string = 'amqp://%s:%s@%s:5672/%s' % (get_env_var('RABBITMQ_DEFAULT_USER'),
                                                        get_env_var('RABBITMQ_DEFAULT_PASS'),
                                                        get_env_var('RABBITMQ_HOST'),
                                                        get_env_var('RABBITMQ_DEFAULT_VHOST'))

# Celery
CELERY_BROKER_URL = f"redis://{get_env_var('RBROKER')}:6379/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_IMPORTS = (
    "apps.bets.tasks",
)
CELERY_RESULT_BACKEND = 'django-db'

# CELERY ROUTESs
CELERY_ROUTES = {
    'apps.admin_panel.tasks.email_template_crm': {'queue': 'email_queue'},
    'apps.admin_panel.tasks.send_sms_crm': {'queue': 'sms_queue'},
    'apps.admin_panel.tasks.transaction_mail': {'queue': 'transaction_email_queue'},
    'apps.admin_panel.tasks.transaction_mail': {'queue': 'ipn_transaction_email_queue'},
    'apps.admin_panel.tasks.newuser_email': {'queue': 'newuser_email_queue'},
    'apps.admin_panel.tasks.queries_email': {'queue': 'queries_email_queue'},
    'apps.admin_panel.tasks.rejection_mail': {'queue': 'offmarket_email_queue'},
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    # ('fr', 'French'),
    # ('ht', 'Haitian'),
    ('cn', 'Chinese'),
]
TIME_ZONE = 'UTC'
USE_TZ = True
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collectstatic')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=2),  # Token expires * hours after being issued
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=10),  # Token can be refreshed up to * 10 after being issued
}


READ_CAPACITY_UNITS = 20
WRITE_CAPACITY_UNITS = 20


DOMAIN_URL = get_env_var('DOMAIN_URL')
CASINO_API_URL = 'https://play.gapi.lol/api/games/post/'
DATA_CONFIG = 922
CASINO_EXIT_URL = get_env_var('CASINO_EXIT_URL')
BASE_URL = get_env_var('BASE_URL')

CASINO_BASE_URL = get_env_var("CASINO_BASE_URL")

LOGIN_URL = '/login'

ASGI_APPLICATION = "api_services.routing.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(get_env_var('RBROKER'), 6379)],
        },
    },
}


BACKGROUND_TASK_RUN_ASYNC = False
MAX_RUN_TIME = 3600 * 3


SYSTEM_PRECISION = 5
MAX_DIGITS = SYSTEM_PRECISION + 15


CASINO_API_KEY = get_env_var('CASINO_API_KEY')
CASINO_PASS_KEY = 'raOegezr5FygydigdwbE9MRieCZEGa7zHx7r18sbAxDxU'
# CASINO_PASS_KEY = get_env_var('CASINO_PASS_KEY')
CASINO_USERNAME = get_env_var('CASINO_USERNAME')
CASINO_PASSWORD = get_env_var('CASINO_PASSWORD')
# AWS s3 bucket details
AWS_S3_BUCKET_NAME = get_env_var("AWS_S3_BUCKET_NAME")

PIX_PAYMENT_API_KEY = get_env_var('PIX_PAYMENT_API_KEY')
PIX_PAYMENT_SECRET_KEY = get_env_var('PIX_PAYMENT_SECRET_KEY')
COINPAYMENTS_API_KEY = get_env_var('COINPAYMENTS_API_KEY')
COINPAYMENTS_API_SECRET = get_env_var('COINPAYMENTS_API_SECRET')
COINPAYMENTS_IPN_URL = get_env_var('COINPAYMENTS_IPN_URL')

FERNET_KEY = get_env_var('FERNET_KEY')
FERNET_SALT = get_env_var('FERNET_SALT')
SERVICE_CREDS_PASSWORD = get_env_var('SERVICE_CREDS_PASSWORD')
# Twillio Details
TWILIO_ACCOUNT_SID = get_env_var('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = get_env_var('TWILIO_AUTH_TOKEN')
TWILIO_VERIFY_SERVICE_SID = get_env_var('TWILIO_VERIFY_SERVICE_SID')
TWILIO_PHONE_NUMBER = get_env_var('TWILIO_PHONE_NUMBER')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = get_env_var('ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = get_env_var('SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = get_env_var('AWS_S3_BUCKET_NAME')
AWS_QUERYSTRING_AUTH = False

PROJECT_DOMAIN = get_env_var('PROJECT_DOMAIN')

SENDGRID_API_KEY = get_env_var('SENDGRID_API_KEY')
SENDGRID_EMAIL = get_env_var('SENDGRID_EMAIL')

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
        ]
    },
}

CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'

REDIS_HOST = get_env_var('REDIS_HOST')

GSOFT_OPERATOR_ID = get_env_var("GSOFT_OPERATOR_ID")
GSOFT_SINATRA_URL = get_env_var("GSOFT_SINATRA_URL")
GSOFT_START_GAME_URL = get_env_var("GSOFT_START_GAME_URL")
GSOFT_HOME_URL = get_env_var("GSOFT_HOME_URL")
GSOFT_EMAIL = get_env_var("GSOFT_EMAIL")
GSOFT_PASSWORD = get_env_var("GSOFT_PASSWORD")
GSOFT_LICENCE = get_env_var("GSOFT_LICENCE")

GSOFT_USER = get_env_var("GSOFT_USER")
GSOFT_GAME_URL = get_env_var("GSOFT_GAME_URL")
GSOFT_LOGIN_URL = get_env_var("GSOFT_LOGIN_URL")
REDIS_PORT = get_env_var('REDIS_PORT')
REDIS_HOST = get_env_var('REDIS_HOST')
PROJECT_DOMAIN = get_env_var('PROJECT_DOMAIN')
NOWPAYMENTS_API_URL = get_env_var('NOWPAYMENTS_API_URL')
NOWPAYMENTS_API_KEY = get_env_var('NOWPAYMENTS_API_KEY')
NOWPAYMENTS_EMAIL = get_env_var('NOWPAYMENTS_EMAIL')
NOWPAYMENTS_PASSWORD = get_env_var('NOWPAYMENTS_PASSWORD')
NOW_PAYMENTS_IPN_SECRET_KEY = get_env_var('NOW_PAYMENTS_IPN_SECRET_KEY')
IPN_CALLBACK_URL = get_env_var('IPN_CALLBACK_URL')
NOW_PAYMENTS_2FA_SECRET_KEY = get_env_var('NOW_PAYMENTS_2FA_SECRET_KEY')
NOW_PAYMENTS_KADO_WIDGET = get_env_var('NOW_PAYMENTS_KADO_WIDGET')
BE_DOMAIN = get_env_var('BE_DOMAIN')
FE_DOMAIN = get_env_var('FE_DOMAIN')
SUCCESS_URL = get_env_var('SUCCESS_URL')
CANCEL_URL = get_env_var('CANCEL_URL')

SESSION_COOKIE_AGE=15*60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
OFF_MARKET_SECRETKEY = get_env_var("OFF_MARKET_SECRETKEY")
OFFMARKET_API_URL = get_env_var("OFFMARKET_API_URL")
ENCRYPTION_KEY = get_env_var("ENCRYPTION_KEY")
ALCHEMYPAY_APPID = get_env_var("ALCHEMYPAY_APPID")
ALCHEMYPAY_SECRETKEY = get_env_var("ALCHEMYPAY_SECRETKEY")
ALCHEMYPAY_URL = get_env_var("ALCHEMYPAY_URL")

CASINO_25_ID = get_env_var("CASINO_25_ID", "")
CASINO_25_URL = get_env_var("CASINO_25_URL", "")
CASINO_25_IMAGE_URL = get_env_var("CASINO_25_IMAGE_URL", "")
CASINO_25_SSLKEY_PATH = get_env_var("CASINO_25_SSLKEY_PATH", "")


CP_GAMES_ID = get_env_var("CP_GAMES_ID")
CP_GAMES_URL = get_env_var("CP_GAMES_URL")
CP_GAMES_APP_ID = get_env_var("CP_GAMES_APP_ID")
CP_GAMES_SECRET = get_env_var("CP_GAMES_SECRET")

TINYMCE_DEFAULT_CONFIG = {
    "height": "550px",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'theme': 'silver',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontsizeselect  | 
            forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    "file_picker_callback": "tinymce_custom_file_picker",
    'content_style': """
        @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap');
        body { font-family: 'Orbitron'; line-height:1 }
    """,
    "skin": "oxide-dark",
    "content_css": "dark",
    'font_formats': 'Orbitron=Orbitron, sans-serif',
    'fontsize_formats': '8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 17pt 18pt 19pt 20pt 21pt 22pt 23pt 24pt 25pt 26pt 27pt 28pt 29pt 30pt 31pt 32pt 33pt 34pt 35pt 36pt',
    'lineheight_formats': '0.50 0.75 1 1.25 1.50 1.75 2',
}

FORTUNEPANDAS_BASE_URL=get_env_var("FORTUNEPANDAS_BASE_URL")
FORTUNEPANDAS_AGENT_NAME=get_env_var("FORTUNEPANDAS_AGENT_NAME")
FORTUNEPANDAS_AGENT_PASSWORD=get_env_var("FORTUNEPANDAS_AGENT_PASSWORD")

MNET_PAYMENT_URL=get_env_var("MNET_PAYMENT_URL")
