from django.conf.urls import url
from django.urls import path

from .views import (AlchemyPayCallback, AlchemyPayCryptoFiatQuery, AlchemyPayCryptoQuery,
    AlchemyPayFiatQuery, Alchemypaytest, AlchemypayTransactionView, CancelWithdrawalCoinpayments, CoinflowBanks, CoinflowCancelTransaction, CoinflowRegisterUserView, CoinflowTotals, CoinflowTransactionView, CoinflowWithdraws,
    ConvertCoins, CreateAlchemyPayOrder, CreateNowPaymentsTestWithdrawal, CreatePaymentAPIView,
    CreatePaymentQrAPIView, CreateTransaction, CreateWithdrawalCoinpayments, GetBalance, GetBankRegistrationLink,
    GetBasicInfo, GetCallbackAddress, GetCoinFlowLink, GetConversionInfo, GetDepositAddress, GetExchangeRates,
    GetIsValidAddress, GetRecentUsedAddress, GetTxnInfo, GetWithdrawalHistory, GetWithdrawalInfo, TestCoinflow,
    ipn_callback, MinAmountView, MnetCallback, MnetTransactionView, NotificationsView,
    NowPaymentsTransaction, NowPaymentsTransactionsAPI, PayoutVerification, QrCodePayment,
    RequestCoinWithdrawal, WithdrawalAPIView, WithdrawalCurrencyAPI)

app_name = "Payments"

urlpatterns = [
    url(r"^qr_code_payment", QrCodePayment.as_view(), name="qr_code_payment"),
    url(r"^notification/", NotificationsView.as_view(), name="notification"),
    path('info/', GetBasicInfo.as_view()),
    path('balance/', GetBalance.as_view()),
    path('create-transaction/', CreateTransaction.as_view()),
    path('txn-info/', GetTxnInfo.as_view()),
    path('create-withdrawal-coinpayments/', CreateWithdrawalCoinpayments.as_view(), name="create-withdrawal"),
    path('create-withdrawal/', RequestCoinWithdrawal.as_view()),
    path('withdrawal-info/', GetWithdrawalInfo.as_view()),
    path('convert-coin/', ConvertCoins.as_view()),
    path('get-callback-addr/', GetCallbackAddress.as_view()),
    path('cancel-withdrawal-coinpayments/', CancelWithdrawalCoinpayments.as_view(), name="rollback-withdrawal"),
    path('get-conversation-info/', GetConversionInfo.as_view()),
    path('rates/', GetExchangeRates.as_view()),
    path('get-withdrawal-history/', GetWithdrawalHistory.as_view()),
    path('get-deposit-address/', GetDepositAddress.as_view()),
    path('create-nowpayments-deposit/', CreatePaymentAPIView.as_view()),
    path('create-nowpayments-withdrawal/', WithdrawalAPIView.as_view()),
    path('ipn_callback_url/', ipn_callback, name='ipn_callback_url'),
    path('nowp-transactions/', NowPaymentsTransaction.as_view(), name='nowp-transactions'),
    path('min-amount/', MinAmountView.as_view(), name='min_amount'),
    path('nowpayments-transactions/', NowPaymentsTransactionsAPI.as_view(), name='nowpayments-transactions'),  
    path('get-currencies/', WithdrawalCurrencyAPI.as_view(), name='get-currencies'),  
    path('create-nowpayments-withdrawals/', CreateNowPaymentsTestWithdrawal.as_view()), 
    path('verify-payout/', PayoutVerification.as_view()),
    path(r"get-recent-casino-address/", GetRecentUsedAddress.as_view(), name="get-recent-casino-address"),
    path(r"get-is-valid-address/", GetIsValidAddress.as_view(), name="get-is-valid-address"),
    path('create-nowpayments-deposit-qr/', CreatePaymentQrAPIView.as_view()),
    path(r"alchemypaytest", Alchemypaytest.as_view(), name="alchemypaytest"),
    path(r"alchemypaydeposit", CreateAlchemyPayOrder.as_view(), name="alchemypaydeposit"),
    path(r"alchemypay-fiat-query", AlchemyPayFiatQuery.as_view(), name="alchemypay-fiat-query"),
    path(r"alchemypay-crypto-query", AlchemyPayCryptoQuery.as_view(), name="alchemypay-crypto-query"),
    path(r"alchemypay-crypto-fiat-query", AlchemyPayCryptoFiatQuery.as_view(), name="alchemypay-crypto-fiat-query"),
    path(r"alchemypay-transactions", AlchemypayTransactionView.as_view(), name="alchemypay-transactions"),
    path(r"alchemypay-callback", AlchemyPayCallback.as_view(), name="alchemypay-callback"),
    path(r"mnet-callback/", MnetCallback.as_view(), name="mnet-callback"),
    path(r"mnet-transactions/", MnetTransactionView.as_view(), name="mnet-transactions"),
    path(r"coinflow-link/", GetCoinFlowLink.as_view(), name="coinflow-link"),
    path(r'test-coinflow', TestCoinflow.as_view(), name='testing-coinflow'),
    path(r"coinflow-bank-link/", GetBankRegistrationLink.as_view(), name="coinflow-link"),
    path(r"coinflow-totals/", CoinflowTotals.as_view(), name="coinflow-totals"),
    path(r"coinflow-banks/", CoinflowBanks.as_view(), name="coinflow-banks"),
    path(r"coinflow-withdraws/", CoinflowWithdraws.as_view(), name="coinflow-withdraws"),
    path(r"coinflow-registration/", CoinflowRegisterUserView.as_view(), name="coinflow-registration"),
    path(r"coinflow-transactions", CoinflowTransactionView.as_view(), name="coinflow-transactions"),
    path(r"coinflow-cancel-transactions", CoinflowCancelTransaction.as_view(), name="coinflow-transactions"),

]
